apiVersion: apps/v1
kind: Project
metadata:
  name: APF opt2
  description: Project for experimenting with Project as code
template:
  name: Agile
  sourceControlType: Git
buildFolders:
  - path: '/CustomFolder'
    permissions:
      - group: 'Team Algis'
        origin: azdo        
        allowed:
          - ViewBuilds
          - QueueBuilds
          - StopBuilds
          - ViewBuildDefinition
          - EditBuildDefinition
          - DeleteBuilds