apiVersion: apps/v1
kind: Project
metadata:
  name: Moim1x
  description: Project for BI Engineering team
template:
  name: Agile
  sourceControlType: Git
teams:
  - name: TheATeam
    description: The A Team
    admins:
      - Timothy Green
      - Linda
repositories:
  - name: AKS-Repo
    permissions:
      - group: 'Database-Adninistrators'
        origin: aad
        allowed:
          - GenericRead
          - GenericContribute
          - CreateBranch
          - PullRequestContribute
      - group: 'Kubernetes-Admins'
        origin: aad
        allowed:
          - GenericRead
          - GenericContribute
          - CreateBranch
          - PullRequestContribute
          - PolicyExempt
environments:
  - name: AksDevelopmentEnvironment
    description: 'Deployment environment for Developers'
    permissions:
      - group: 'Database-Adninistrators'
        origin: aad
        roles: 
          - User
buildFolders:
  - path: '/AKSBuilds'
    permissions:
      - group: 'Database-Adninistrators'
        origin: aad
        allowed:
          - ViewBuilds
          - QueueBuilds
          - StopBuilds
          - ViewBuildDefinition
          - EditBuildDefinition
          - DeleteBuilds
releaseFolders:
  - path: '/AksReleases'
    permissions:
      - group: 'Database-Adninistrators'
        origin: aad
        allowed:
          - ViewReleaseDefinition
          - EditReleaseDefinition
          - ViewReleases
          - CreateReleases
          - EditReleaseEnvironment
          - DeleteReleaseEnvironment
          - ManageDeployments