apiVersion: apps/v1
kind: Project
metadata:
  name: BI-Engineering
  description: Project for BI Engineering team
template:
  name: Agile
  sourceControlType: Git
repositories:
  - name: BI-Examples-Repo
