apiVersion: apps/v1
kind: Project
metadata:
  name: BI-Engineering
  description: Project for BI Engineering team
template:
  name: Agile
  sourceControlType: Git
repositories:
  - name: BI-Examples-Repo
    permissions:
      - group: 'Database-Adninistrators'
        origin: aad
        allowed:
          - GenericRead
          - GenericContribute
          - CreateBranch
          - PullRequestContribute
      - group: 'Kubernetes-Admins'
        origin: aad
        allowed:
          - GenericRead
          - GenericContribute
          - CreateBranch
          - PullRequestContribute
          - PolicyExempt
environments:
  - name: DevelopmentEnvironment
    description: 'Deployment environment for Developers'
    permissions:
      - group: 'Database-Adninistrators'
        origin: aad
        roles: 
          - User
buildFolders:
  - path: '/moim-test'
    permissions:
      - group: 'Database-Adninistrators'
        origin: aad
        allowed:
          - ViewBuilds
          - QueueBuilds
          - StopBuilds
          - ViewBuildDefinition
          - EditBuildDefinition
          - DeleteBuilds
releaseFolders:
  - path: '/example-releases'
    permissions:
      - group: 'Database-Adninistrators'
        origin: aad
        allowed:
          - ViewReleaseDefinition
          - EditReleaseDefinition
          - ViewReleases
          - CreateReleases
          - EditReleaseEnvironment
          - DeleteReleaseEnvironment
          - ManageDeployments