apiVersion: apps/v1
kind: AreaPathSecurity
metadata:
  name: AreaPathSecurity
  description: Sample that applies permissions across multiple area paths
permissions:
  - paths:
    - Platform/Marketing/Frontdesk
    - Platform/Finance
    allowed:
    - GENERIC_READ
    - GENERIC_WRITE
    - CREATE_CHILDREN
    - DELETE
    - WORK_ITEM_READ
    - WORK_ITEM_WRITE
    - MANAGE_TEST_PLANS
    - MANAGE_TEST_SUITES
    groups: 
    - group: 'K8s-Operators'
      origin: Aad
      aadObjectId: eb2a16c0-401a-4fc8-beb4-02fe3e6f25b6
    users:
    - name: Timothy
      principal: timothy@moimhossainhotmail.onmicrosoft.com