apiVersion: apps/v1
kind: IterationPathSecurity
metadata:
  name: IterationPathSecurity
  description: Sample that applies permissions across multiple Iteration paths
permissions:
  - paths:
    - Platform/GA
    - Platform/GA/CommunityRelease
    - Platform/GA/CTP1
    allowed:
    - GENERIC_READ
    - GENERIC_WRITE
    - CREATE_CHILDREN
    - DELETE
    groups: 
    - group: 'K8s-Operators'
      origin: Aad
      aadObjectId: eb2a16c0-401a-4fc8-beb4-02fe3e6f25b6
    users:
    - name: Timothy
      principal: timothy@moimhossainhotmail.onmicrosoft.com