apiVersion: apps/v1
kind: ReleaseFolderSecurity
metadata:
  name: ReleaseFolderSecurity
  description: Sample that applies permissions across multiple release folders
permissions:
  - paths:
    - \Demo-Folder\Child-Folder\X86
    - \Demo-Folder\Child-Folder\X64
    allowed:
    - ViewReleaseDefinition
    - EditReleaseDefinition
    - ViewReleases
    - CreateReleases
    - EditReleaseEnvironment
    - DeleteReleaseEnvironment
    - ManageDeployments 
    groups: 
    - group: 'K8s-Operators'
      origin: Aad
      aadObjectId: eb2a16c0-401a-4fc8-beb4-02fe3e6f25b6
    users:
    - name: Timothy
      principal: timothy@moimhossainhotmail.onmicrosoft.com