apiVersion: apps/v1
kind: Project
metadata:
  name: Tulsa
  description: Project for BI Engineering team
template:
  name: Agile
  sourceControlType: Git
permissions:
  - name: Project Administrators
    membership:
      groups:
        - name: 'ACL-ROOT'
          id: 2dec2374-3c51-4743-b247-ad6f80ce4f0b
      users:
        - name: Timothy Green
          id: 4ae3c851-6ef3-4748-bef9-4f809736d538
        - name: Moim Hossain
          id: d1724c62-a3be-416f-8735-77262fa93b9c
  - name: Contributors
    membership:
      groups:
        - name: 'IoT-Developers'
          id: 00238ebc-66c1-4220-a859-ed0a00243f27
      users:
        - name: Timothy Green
          id: 4ae3c851-6ef3-4748-bef9-4f809736d538
        - name: Linda
          id: 9c5918c7-ef03-4059-a49e-aa6e6d761423
teams:
  - name: TulsaPeople
    description: The A Team
    admins:
      - name: Timothy Green
        id: 4ae3c851-6ef3-4748-bef9-4f809736d538
      - name: Linda
        id: 9c5918c7-ef03-4059-a49e-aa6e6d761423
    membership:
      groups:
        - name: 'Kubernetes-Admins'
          id: a2931c86-e975-4220-aa89-dc3f952290f4
      users:
        - name: Timothy Green
          id: 4ae3c851-6ef3-4748-bef9-4f809736d538
        - name: Linda
          id: 9c5918c7-ef03-4059-a49e-aa6e6d761423
repositories:
  - name: Temp
    permissions:
      - group: 'Database-Adninistrators'
        origin: aad
        allowed:
          - GenericRead
          - GenericContribute
          - CreateBranch
          - PullRequestContribute
      - group: 'Kubernetes-Admins'
        origin: aad
        allowed:
          - GenericRead
          - GenericContribute
          - CreateBranch
          - PullRequestContribute
          - PolicyExempt
