apiVersion: apps/v1
kind: RepositorySecurity
metadata:
  name: RepositorySecurity
  description: Sample that applies permissions across multiple repositories
permissions:
  - applyToRoot: true
    allowed:
    - GenericRead
    - GenericContribute
    - CreateBranch
    - DeleteRepository
    - RenameRepository 
    - PullRequestContribute
    - PullRequestBypassPolicy
    groups: 
    - group: 'K8s-Operators'
      origin: Aad
      aadObjectId: eb2a16c0-401a-4fc8-beb4-02fe3e6f25b6
    users:
    - name: Timothy
      principal: timothy@moimhossainhotmail.onmicrosoft.com
  - names:
    - React-JS
    - Mobile-App
    - SQL-DemoRepo
    allowed:
    - GenericRead
    - GenericContribute
    - CreateBranch
    - DeleteRepository
    - RenameRepository 
    - PullRequestContribute
    - PullRequestBypassPolicy
    groups: 
    - group: 'K8s-Operators'
      origin: Aad
      aadObjectId: eb2a16c0-401a-4fc8-beb4-02fe3e6f25b6
    - group: 'Frontend-Engineers'
      origin: Aad
      aadObjectId: 95e3d281-c6e3-4ed6-af34-d0d8d46c9693      
    users:
    - name: Timothy
      principal: timothy@moimhossainhotmail.onmicrosoft.com