apiVersion: apps/v1
kind: Project
metadata:
  name: Security-As-Code
  description: Project for BI Engineering team
template:
  name: Agile
  sourceControlType: Git
buildFolders:
  - path: '/AKSBuilds'
    permissions:
      - group: 'Database-Adninistrators'
        origin: aad
        id: 04dcbbaf-614d-4614-8f08-37a54de80504
        allowed:
          - ViewBuilds
          - QueueBuilds
          - StopBuilds
          - ViewBuildDefinition
          - EditBuildDefinition
          - DeleteBuilds