apiVersion: apps/v1
kind: Team
metadata:
  name: TAS-Main
environments:
  - name: UnprCluster
    description: 'Deployment environment for Developers'
    serviceEndpointReference: UnprEndpoint
    permissions:
      - group: 'Database-Adninistrators'
        origin: aad
        id: 04dcbbaf-614d-4614-8f08-37a54de80504
        roles: 
          - User