apiVersion: apps/v1
kind: Repository
metadata:
  name: TAS-Main
repositories:
  - name: Temp
    permissions:
      - group: 'Database-Adninistrators'
        origin: aad
        allowed:
          - GenericRead
          - GenericContribute
          - CreateBranch
          - PullRequestContribute
      - group: 'Kubernetes-Admins'
        origin: aad
        allowed:
          - GenericRead
          - GenericContribute
          - CreateBranch
          - PullRequestContribute
          - PolicyExempt
