name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      imagetag: v1
    steps:
    - uses: actions/checkout@v2
    - name: Login to github packages
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u moimhossain --password-stdin
    - name: Build the Docker image
      working-directory: ./src/azdoctl/Kdoctl
      run: docker build . --file Dockerfile --tag ghcr.io/moimhossain/azdoctl:${imagetag}
    - name: Push to github packages
      run: docker push ghcr.io/moimhossain/azdoctl:${imagetag}
